export const GETTPRODUCTS_REQUEST = "GETTPRODUCTS_REQUEST";
export const GETTPRODUCTS_SUCCESS = "GETTPRODUCTS_SUCCESS";
export const GETTPRODUCTS_FAILURE = "GETTPRODUCTS_FAILURE";

export const ADDPRODUCTS_REQUEST = "ADDPRODUCTS_REQUEST";
export const ADDPRODUCTS_SUCCESS = "ADDPRODUCTS_SUCCESS";
export const ADDPRODUCTS_FAILURE = "ADDPRODUCTS_FAILURE";